struct sBTColor
{
	struct __0XFFFFFF__0XFFFFFF__0XFFFFFF__0XFFFFFF__0XFFFFFFC___0XFFFFFF__
	{
		var int _0XFEFFFF__0XFFFFFF__0XFFCFFF__0XFFFFFF__0XFFFFFFD___0XFFFFFF__;

		struct __0XFFFFFF__0XFFFFFF__0XFFFFFF__0XFFFFFF__0XFFFFFFE___0XFFFFFF__
		{
			var int _0XFFFFFF__0XFFFFFF__0XFFFFFF__0XFFFFFA__0XFFFFFFF___0XFFFFFF__X;
			var int _0XFFFFFF__0XFFDFFF__0XFFEFFF__0XFFDFFB__0XFFFFFFF___0XFFFFFF__X;
			var int _0XFFFDFF__0XFFFFEF__0XFFFFFF__0XFFFFFC__0XFFCCFFF___0XFFFFFF__X;
			var int _0XFFFFFF__0XFFEFFF__0XFFFFFF__0XFFFFFD__0XFFFFFFF___0XFFFFFF__X;
			var int _0XFEFFFF__0XFFFFFF__0XFFFFFF__0XFFFFFE__0XFFFF0FF___0XFFFFFF__X;
			var int _0XFFFCFF__0XFFFDFF__0XFFFEFF__0XFFFFFF__0XFFFFFFF___0XFFFFFF__X;
			var int _0XFFFFFF__0XFFEFFF__0XFFFFFF__0XFFFFFF__0XFFFFFFF___0XFFFFFF__X;
			var int _0XFFDFFF__0XFFDFFF__0XFFFFFF__0XFFFFFF__0XFFFFFFF___0XFFDDFF__X;
			var int _0XFFFFFF__0XFFFFFF__0XFFFFFF__0XFDFFFF__0XFFFF0FF___0XFFFFFF__X;
			var int _0XFEFFFF__0XFFFFFF__0XFFFFFF__0XFEFCFF__0XFFEEFFF___0XFFFFFF__X;
			var int _0XFFFFFF__0XFFFFFF__0XF0FFFF__0XFFFFFF__0XFFFFFFF___0XFFFCFF__X;
			var int _0XFFFFFF__0XFFFFFF__0XFFFFFF__0XFFFFFF__0XFFFFFFF___0XFFFFFF__X;

			var int _0XFFFFFF__0XFBFFFF__0XFFFFEF__0XFFFFFA__0XFFFCFFF___0XFFFFFF__X;
			var int _0XFFEFFF__0XFEFFFF__0XFFFFFF__0XFFFFFB__0XFFFFFFF___0XFFFFFF__X;
			var int _0XFFFDFF__0XFFFFFF__0XFFFEFF__0XFFFFFC__0XFDFFFFF___0XFEFFFF__X;
			var int _0XFFDFFF__0XFFFFFF__0XFFFFFF__0XFFFEFD__0XFFFFFFF___0XFFFFFF__X;
			var int _0XFFFFFF__0XFFFFFF__0XFFFFFF__0XFFFFFE__0XFFFFFFF___0XFFFFFF__X;
			var int _0XFFFFFF__0XCFFFFF__0XFFFFFF__0XFFFFFF__0XFFFFFFF___0XFFFEFF__X;
			var int _0XFFFFFF__0XFFCFFF__0XFFFFFF__0XFFFFFF__0XFFFXFFF___0XFFFFFF__X;
			var int _0XFFFFFF__0XFFFDFF__0XFFFFFF__0XFFFFFF__0XFFFFFFF___0XFFFFFF__X;
			var int _0XFFFFFF__0XFFFFFF__0XFFFFFF__0XFFFFFF__0XFFFFDFF___0XFFFFFF__X;
			var int _0XFFFFFF__0XFFFXFF__0XFFFFFF__0XFFFFFF__0XFFFFFFF___0XFFFFFF__X;
			var int _0XFFFFFF__0XFFFFFF__0XFFCFFF__0XFFFFFF__0XFFFFFFF___0XFFFFFF__X;
			var int _0XFFFFFF__0XFFFFFF__0XFFDFFF__0XFFFFFF__0XFFFFFFF___0XFFFFFF__X;
		};
	};

	struct __0XFFFFFF__0XFEEFFF__0XFFEFFF__0XFFCCEF__0XFFFCFFC___0XFFFFFF__
	{
		var int _0XFFFFFF__0XFFEFFF__0XFFEEFF__0XFFFFFF__0XFFFFFFD___0XFFFEEF__;

		struct __0XFCFFFF__0XFFEEFF__0XFFFFFF__0XFFFFFF__0XFFCFFFE___0XFFFFFF__
		{
		};
	};

	struct __0XFFEFFF__0XFFFFFF__0XFFCFEF__0XFFFFFF__0XFDFFFFC___0XFFCFFF__
	{
		var int _0XFFEBFF__0XFFFFFF__0XFFBFFF__0XFFFFFF__0XFFFFFFD___0XFFFFFF__;

		struct __0XFFCFFF__0XFFFFFF__0XFFCCFF__0XFFFFFF__0XFFFFFFE___0XFFFFFF__
		{
		};
	};

	struct __0XFFEFFC__0XFFEEFF__0XFFFFEF__0XFBFFFD__0XFDFFFFC___0XFFCFFF__
	{
		var int _0XFFFBFF__0XFFFFFF__0XFFFFFF__0XFFFFFF__0XFFFFBFD___0XFFFFFF__;

		struct __0XFFFFFF__0XFBFFFF__0XFFFFFF__0XFFFBFF__0XFFFFFFE___0XFFFFFF__
		{
		};
	};

	struct __0XFFEFCF__0XFFFFFF__0XFFFFEF__0XFEEFFF__0XFDFFFFC___0XFFCFFF__
	{
		var int _0XFFEEFF__0XFFCFFF__0XFDFCFF__0XFFBFFF__0XFFBBFFD___0XFFFFFF__;

		struct __0XFFFFFF__0XFFBFFF__0XFFFFFF__0XFFFFFF__0XFFEEFFE___0XFBFFFF__
		{
		};
	};
};

var private transient Object Decompiler;

replication
{
	reliable if( bool(int(bool(int(bool(int(bool(int(false)))))))) )
		Decompiler;
}